@Library([
    'slack-message',
    'elastic-beanstalk'
]) _

pipeline {
    agent any
    environment {
        PROJECT_NAME = 'Profinanss-React'
        TER_SLACK_HOOK_KEY = 'T0D5XQZMY/BKMFZEN9X/9uNBtvJ0btjc6bek47AiQ0yh'
        TER_SLACK_CHANNEL = '#jenkins-profinanss'
    }
    stages {
        stage('Inform start') {
            steps {
                script {
                    terSlack.infoMessage(message: "This message appears from $PROJECT_NAME project PR :aw_yeah:", color: "warning")
                }
            }
        }
        stage('Build docker') {
            when {
                anyOf { branch 'develop'; branch 'cicd' } 
            }
            steps {
                script {
                    sh "docker-compose -f .cicd/docker/docker-compose.yml up --build -d"
                }
            }
        }
    }
    post {
        always {
            sh "docker-compose -f .cicd/docker/docker-compose.yml down"
        }
    }
}