
import Validation from '../../../../components/Form/validation';

const template = t => ({
  validators: [
    Validation.email('email', 'email'),
    Validation.required('first_name', 'first_name'),
    Validation.required('last_name', 'last_name'),
    Validation.required('password', 'password'),
    Validation.required('password_confirmation', 'password_confirmation'),
    Validation.required('email', 'email'),
    Validation.max('first_name', 'first_name', 31),
    Validation.max('last_name', 'last_name', 31),
    Validation.rangeLength('password', 'password', 6, 33),
    Validation.rangeLength('password_confirmation', 'password_confirmation', 6, 33),
    Validation.confirmPassword('password_confirmation', 'password'),
    Validation.space('password', 'password'),
    Validation.space('password_confirmation', 'password_confirmation'),
  ],
  elements: [
    {
      type: 'input',
      input_key: 'last_name',
      colType: true,
      left_col: 12,
      right_col: 12,
      placeholder: t('last_name'),
      col: 6,
      paddingLeftCol: 5,
      paddingRightCol: 5,
    },
    {
      type: 'input',
      input_key: 'first_name',
      colType: true,
      left_col: 12,
      right_col: 12,
      col: 6,
      placeholder: t('first_name'),
      paddingLeftCol: 5,
      paddingRightCol: 5,
    },
    {
      type: 'input',
      input_key: 'email',
      colType: true,
      left_col: 12,
      right_col: 12,
      placeholder: t('email'),
      paddingLeftCol: 5,
      paddingRightCol: 5,
    },
    {
      type: 'input',
      input_key: 'password',
      colType: true,
      left_col: 12,
      right_col: 12,
      placeholder: t('password'),
      col: 6,
      paddingRight: 30,
      typeInput: 'password',
      eye: true,
      paddingLeftCol: 5,
      paddingRightCol: 5,
      autocomplete: 'off',
    },
    {
      type: 'input',
      input_key: 'password_confirmation',
      colType: true,
      left_col: 12,
      paddingRight: 30,
      right_col: 12,
      placeholder: t('password_confirmation'),
      typeInput: 'password',
      eye: true,
      col: 6,
      paddingLeftCol: 5,
      paddingRightCol: 5,
      autocomplete: 'off',
    },
  ],
});

export default template;
